### ISSUE TITLE
HIDAPI relay support?

### ISSUE THREAD

**Issue by Dh0mp5eur** [ondrej1024/crelay#1]
Hello,
I would like to know the USB relay based on HIDAPI are supported or hard to add support?
https://github.com/darrylb123/usbrelay

I'm interested by HTTP API.

Thx

**Comment by ondrej1024** [comment]
Thanks for the link to this project. I didn't know this type of relay card with USB HIDAPI. Looks interesting, even though the manufactures web site www.dcttech.com has disapeared, so it might be difficult to get hold of these cards in the future.

I have just asked the guys over there form the usbrelay project if they want to contribute and integrate their driver software into crelay. It shouldn't be too difficult. Their code seems quite straight forward.

We'll see if they are interested,
Ondrej

**Comment by Dh0mp5eur** [comment]
Thanks
This cards are a very good price on aliexpress (~10$).
And they are more simple (1 or 2 relay).
I just need a card with a single relay.
Supported cards are too expensive for my small project.

**Comment by ondrej1024** [comment]
I have added support for these HID API compatible relay cards in the hidapi_experimantal branch. However I don't have this kind of card and cannot test. Do you have one and can test this? Would be great.

**Comment by Dh0mp5eur** [comment]
I will receive soon.
Thx

**Comment by Dh0mp5eur** [comment]
I tested and it works perfectly.
Thx

**Comment by ondrej1024** [comment]
Great, thanks for testing. 
HID API support is now merged into master branch and officially released in version 0.7.  Issue resolved.
Ondrej
