### ISSUE TITLE
I have issue with turning my relay on and off. 

### ISSUE THREAD

**Issue by Bhanushree2904** [ondrej1024/crelay#17]
Hi, 

I am new in using relays, I see this  https://www.raspberrypi.org/forums/viewtopic.php?t=110710 Please Help Noobs control 8 channel relay post and issues regarding it. 
I have everything installed and I have connected my raspberry pi to a 8 channel usb relay. The device is detected. 

pi@raspberrypi ~ $ sudo crelay -i
Detected relay cards:
#1 Sainsmart USB 4/8 channel relay card (serial AI04XQI3)
pi@raspberrypi ~ $sudo crelay 1 on
pi@raspberrypi ~ $ 

I have it up to the above point. I cannot turn on the relay or turn it off. I get no output!!! Please help. Thanks in advance.

**Comment by Bhanushree2904** [comment]
I have this working after reconnecting the power source to my relay!! Thanks :)

**Comment by ondrej1024** [comment]
> I have this working after reconnecting the power source to my relay!!

That's what I thought :smiley:

**Comment by Anushree2904** [comment]
Hi, 

I have a quick question. Can I control the relays to on and off for certain number of seconds from the command line? using  $ sudo crelay 1 on method ? 

Thanks, 
Bhanu

**Comment by ondrej1024** [comment]
No, this feature is not implemented from command line, only for Web GUI. To use this function from command line we could implement something like this:
` $ sudo crelay 1 pulse`

If you know to code in C you could provide a patch with this feature. Otherwise just open a new issue with this feature request.
