### ISSUE TITLE
Installing to Debian Stretch

### ISSUE THREAD

**Issue by dlewin** [ondrej1024/crelay#18]
libudev won't install until you : 
- sudo apt-get install pkg-config libusb-dev

**Comment by ondrej1024** [comment]
libudev should only be needed if you build the HIDAPI lib from source. But in recent Debian releases the [libhidapi-dev package](https://packages.debian.org/stretch/libhidapi-dev) can be installed from the Debian repos.
Did you try this?

**Comment by dlewin** [comment]
Actually it was for the doc. part. Thus following the provided steps I have installed :

- libftdi1
- libhidapi-libusb0
- libusb-1.0-0
- libftdi1
- libftdi-dev
- libhidapi-libusb0
- libhidapi-dev
-  libusb-1.0-0
- libusb-1.0-0-dev
- libudev-dev

and the configure was not possible until : 

- dh-autoreconf
- pkg-config libusb-dev

**Comment by ondrej1024** [comment]
You don't need to run `configure` at all. This is part of the optional installation step "Build dependencies from source" which should not be needed on Debian Stretch if the previous step "Install dependencies" was successful. 
I think I will just delete the optional step from the doc as most people will not run Debian Wheezy or older anymore.

**Comment by dlewin** [comment]
ok
