### ISSUE TITLE
Listen interface

### ISSUE THREAD

**Issue by Dh0mp5eur** [ondrej1024/crelay#2]
Is possible to control the HTTP Server listen on 127.0.0.1?
Thx

**Comment by ondrej1024** [comment]
Of course, just change the following line (499) in crelay.c
    `sin.sin_addr.s_addr = INADDR_ANY;`
to
    `sin.sin_addr.s_addr = INADDR_LOOPBACK;`

In a future release I might introduce a configuration file and make this configurable with a parameter.
Ondrej

**Comment by Dh0mp5eur** [comment]
Ok Thx
