### ISSUE TITLE
Get this to work on Standard linux

### ISSUE THREAD

**Issue by lseg74** [ondrej1024/crelay#32]
Hi,

Will this project only work in a OpenWrt environment. Or can I get this to work on a standard Linux PC.
If yes, how?
I am somewhat missing How to get this to work for me. And I really would like to get this to work.

Kind regards,

Luc

**Comment by ccutrer** [comment]
I have it running on Ubuntu bionic, amd64 machine. I just followed the Installation From Source instructions in the readme - basically install all the dependencies, download the code, `make`. it has to be run as root, so I also set the setuid bit so that I could call it from less-privileged code.

**Comment by ondrej1024** [comment]
> I am somewhat missing How to get this to work for me.

Hi Luc, did you read the documentation? As @ccutrer wrote, everything is described in the README. 

For OpenWrt there are ready to use packages so it is very simple to install crelay from their repositories, but for all other platforms you need to build the software as described.

**Comment by lseg74** [comment]
I am really sorry, for some reason I missed this. It couldnt have been clearer.
Is this also enough to get the HTTP api working?

My final purpose is to get this working in a Docker container, not sure when I will find time for this.

**Comment by ondrej1024** [comment]
> Is this also enough to get the HTTP api working?

Yes, HTTP api is always enabled when running `crelay` in daemon mode.
