### ISSUE TITLE
Compliments !

### ISSUE THREAD

**Issue by 12finger** [ondrej1024/crelay#39]
Great great work! Simply amazing.
Everything went nice and smooth. Installation on Ubuntu 18.04 without any hiccups.
Just wanted to say thank you ❤️ 🚀

**Comment by 12finger** [comment]
sorry for this double post!
i truly meant it 🤟

**Comment by 12finger** [comment]
ps: feel free to `delelte` this doublette issue/comment

**Comment by ondrej1024** [comment]
Thanks. It's always nice to have some feedback even if things are working fine. Usually people only get back if somethings not working. So you never know how many people are happy with what you did.
Cheers.
