### ISSUE TITLE
Driver patch for kernel 3.18.12+

### ISSUE THREAD

**Issue by Schaussi** [ondrej1024/crelay#4]
Hi,

would you mind publishing a new driver binary for the current Raspbian kernel?
Thank you!

**Comment by ondrej1024** [comment]
I might do this but I need some time. Last year I got my PC stolen with the Virtual Machine where I had the RPi kernel cross compile e environment installed. So I have to set this up again. Therefore it won't happen tomorrow or next week.
But maybe I could asked the RPi kernel maintainers, if they could include the cp210x patch in the kernel they release for the RPi. In this way I wouldn't have to build a kernel module for each new kernel version.
Ondrej

**Comment by ondrej1024** [comment]
Hi Schaussi,
I have completely rewritten the Conrad card driver and now we don't need cp210x kernel driver any more. _crelay_ talks directly to the card and it works great without driver patch.
It would be nice if you could try the latest version and send me your feedback. Thanks.

**Comment by ondrej1024** [comment]
From version 0.8 onwards, the cp210x driver is not needed any more. Closing this issue.
