### ISSUE TITLE
USB relay detection

### ISSUE THREAD

**Issue by boscotronics** [ondrej1024/crelay#48]
I have a Sainsmart usb relay card and an ICOM 7300 ham radio that is also usb controlled.  Each works well independent of the other.  I have tried using different usb ports but I am having usb conflicts.  When I type in crelay -i, I get the Sainsmart relay card and a Conrad card marked as icom7300.  When I try to use the Sainsmart card, it will allow me to turn a relay on but returns this error 'libusb_control_transfer error (LIBUSB_ERROR_PIPE)' if I try to turn a relay off.  I've loaded the driver for the Sainsmart card only.

Is there something in the detection part of the program that I could modify to just have it look for that card and nothing else?

John Kosobucki
kosobucki.john@gmail.com

**Comment by ondrej1024** [comment]
@boscotronics 
Sorry for the late answer. Are you still having this problem or have you figured out a solution?

**Comment by boscotronics** [comment]
Figured it out.

I had to read the instructions for your program a little closer...

John
